spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://:3306/myapp
    username:
    password:
    type: com.alibaba.druid.pool.DruidDataSource

  servlet:
  multipart:
    max-request-size: 5GB  # 上传文件总的最大值 默认10MB
    max-file-size: 1GB #单个文件最大值 默认10MB
#  redis:
#
#    host: 192.168.232.129
#    port: 6379

owner:
  qqNumber: "" #机器人创建者的qq号，用来确认机器人发状态信息的对象和发送自定义消息的支配者

bot:
  qqNumber: "" #机器人自己的qq号

##静态资源对外暴露的访问路径
#  file.staticAccessPath=/api/file/**
#  #文件上传目录（注意Linux和Windows上的目录结构不同）
#  #file.uploadFolder=/root/uploadFiles/
#  file.uploadFolder=d://uploadFiles/
shiro:
  loginUrl: /static/hello.html
server:
  port: 1688
